# Generated by Django 3.2.25 on 2024-12-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True},
        ),
    ]
