# Generated by Django 3.2.25 on 2024-12-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
    ]
