# Generated by Django 3.2.25 on 2024-12-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0003_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
    ]
