# Generated by Django 3.2.25 on 2024-12-07 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0004_alter_player_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sportsApp.person'),
        ),
    ]
