# Generated by Django 3.2.25 on 2024-12-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0005_auto_20241207_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
